function [ rot_mat ] = MOB(  X , a )
%% MohamedRaslan .. Muhammed Mohhie
   switch X
   case {'X','x'} 
        rot_mat = [1      0          0      a ;...
                   0      1          0 0 ;...
                   0 0  1 0 ;...
                   0       0         0      1 ];  
   case {'Y','y'} 
        rot_mat =   [ 1  0 0 0 ;...
                      0  1 0 a ;...
                      0  0 1 0 ;...
                      0  0       0     1];  
   case {'Z','z'} 
        rot_mat =     [ 1         0         0  0 ;... 
                        0         1         0  0 ;... 
                        0         0         1  a ;...
                        0         0         0  1 ]; 
   end
end
